### ISSUE TITLE
Sitrep?

### ISSUE THREAD

**Issue by Tirpitz93** [intercept/intercept-python#2]
Hello,
What is the current status of this project, are we still waiting for: 
https://github.com/intercept/intercept/issues/110 as mentioned in https://github.com/intercept/intercept/issues/168?

cheers
Lonja

**Comment by dedmen** [comment]
This is a issue tracker not a progress requester ;)
Yes we are waiting on the implementation of helper classes. 
The layout of them was already planned out

**Comment by Tirpitz93** [comment]
re waiting for https://github.com/intercept/intercept/issues/110, wouldnt it be easier to build the objects in python  to build the higher level constructs?

**Comment by Zakant** [comment]
Sure, but that is quite a lot of work to do and I honestly don't have the time and muse to start with it. I hoped I could use the classes from the helper library and only extend them here and there. Feel free to build something and pr it, even if it's just a tiny bit ;)

**Comment by overfl0** [comment]
Has anyone taken a look at pybind11 in the meantime?

I have some time ago and they promise *extending* python to be simpler and more straightforward than boost (because they don't have the burden of the forced compatibility with 10000s of architectures out there, as it is the case with Boost).
On the other hand, they say that *embedding* python (what we actually want to do!) isn't very polished. You can do so but (I think!) you can expect to have some rough time doing a few things.

What's really putting me off for working on intercept-python right now is the amount of things that have to be done in order to have a fully functioning setup with boost (and this also takes into account intercept itself, especially that I haven't modded arma in SQF previously so "I'm not the target audience for Intercept" anyway :-/). At least, that was the case a few months ago.
And each time I had some free time that I could dedicate to Intercept-python I was discouraged by the fact that I'll have to set everything up again and never did it as a result.

I'm still offering my Pythia code in parts or as a whole (pure CPython embedding).

**Comment by Tirpitz93** [comment]
I have been looking into various routes for embedding. But as my C/C++ knowledge is very rudimentary it all looks quite confusing.  The only thing I have done so far is https://github.com/Tirpitz93/a32s.
Is there any way we could use the system `PYTHON` path variable and run the code in that interpreter, then we wouldn't have to compile it in our project and the end user would be able to run whichever version they choose.

**Comment by overfl0** [comment]
I think that this belongs more to the #1 topic and it's all more complicated than just using one `PYTHON` path variable. See #1 for my response.

**Comment by jonpas** [comment]
Does not belong on issue tracker, please join our Slack if you want to discuss that.

To be clear, discussions about open issues or pull requests are fine, overall design discussions, asking for status on X does not belong on the issue tracker.

Let's keep it clean and organized.

**Comment by Tirpitz93** [comment]
apologies, also not sure if it is just me but i cant connect to the slack given in the intercept/intercept readme (http://slackin-intercept.idi-systems.com/).

**Comment by dedmen** [comment]
technician was notified. (Germans will understand this)

**Comment by overfl0** [comment]
I don't want to spam the issue tracker but you already have an account on that slack - I can see your username there is `Tirpitz` (but I guess that won't help you getting in).
Anyway, try recovering your password maybe. @Tirpitz93
